### ISSUE TITLE
`version` is not updated ("lockfileVersion": 2) in the package-lock.json

### ISSUE THREAD

**Issue by vansergen** [semantic-release/npm#340]
The package version is not updated in the `packages` section. [Here](https://github.com/vansergen/poloniex-node-api/blob/0a90490898bebdf93b3349314a58a42e0fb10d51/package-lock.json#L8) is an example (applies only to `"lockfileVersion": 2`).

**Comment by danez** [comment]
This should now be fixed when you try to upgrade to version `7.1.0` of `semantic-release/npm`. Prior versions where not using npm v7

**Comment by nschonni** [comment]
I'm still seeing this with v8. It updates the top version number, but not the interior `version` that package-lock v2 has https://github.com/htmlhint/HTMLHint/commit/e91efe9c4368f787386f42c18993db8700f469cf

**Comment by pedronfigueiredo** [comment]
We are still seeing a mismatch on package-lock.json. Is this a planned feature? thanks
